Repository wecode-bootcamp-korea/37-1st-ZINWOOS-frontend, pull requests merged in 2022-09, with the labels that each got.

#1 [37기 조재현] Add: Nav 기본 레이아웃 구성 및 로그인&회원가입 기능 구현 완료
  public/index.html
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/Nav/Dropdown.js
  src/components/Nav/Dropdown.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/variable.scss
Labels: Conflict 해결 요청, 수정 요청

#10 [37기 안나라] Refactor: 상세페이지 코드리팩토링
  public/data/item.json
  src/Router.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/components/PriceCalculator.js
  src/pages/ProductDetail/components/PriceCalculator.scss
  src/pages/ProductDetail/components/ProductImg.js
  src/pages/ProductDetail/components/ProductImg.scss
Labels: 멘토 리뷰 요청

#11 [37기 이가을] Modify: footer CSS 수정
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#7 [37기 조재현] Refactor : 리팩토링 리뷰 반영 완료 및 merge 요청드립니다!
  public/data/cart.json
  public/index.html
  src/Router.js
  src/components/Login/Login.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/ListTable.js
  src/pages/Main/Carousel.scss
  src/pages/Main/Main.scss
Labels: 멘토 리뷰 요청, 추가 기능 구현 중

#14 [37기 안나라] Modify: sub nav 수정
  src/components/SubNav/SubNav.js
  src/components/SubNav/SubNav.scss
Labels: 멘토 리뷰 요청

#13 [37기 안나라] 상세페이지 장바구니 & 위시리스트 통신완료, 상세설명 컴포넌트 추가
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/components/PriceCalculator.js
  src/pages/ProductDetail/components/ProductImg.scss
  src/pages/ProductDetailTab/ProductDetailTab.js
  src/pages/ProductDetailTab/ProductDetailTab.scss
  src/pages/ProductDetailTab/components/DetailTab.js
  src/pages/ProductDetailTab/components/DetailTab.scss
  src/pages/ProductDetailTab/components/QaTab.scss
  src/pages/ProductDetailTab/components/RefundTab.scss
  src/pages/ProductDetailTab/components/ReviewTab.scss
Labels: 멘토 리뷰 요청

#15 [37기 이가을] Modify: 상세상품 Link 설정!
  public/data/likeData.json
  src/pages/Likes/Likes.js
Labels: 멘토 리뷰 요청

#17 [37기 안나라] Modify: 리뷰반영 및 상세페이지 내 컴포넌트 추가
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/components/PriceCalculator.js
  src/pages/ProductDetail/components/ProductImg.scss
  src/pages/ProductDetailTab/components/DetailTab.scss
Labels: 멘토 리뷰 요청

#18 [37기 안나라] Modify: Subnav link 추가
  src/components/SubNav/SubNav.js
  src/components/SubNav/SubNav.scss
Labels: 멘토 리뷰 요청

#19 [37기 이가을] Modify: 로고 / CSS 수정
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#20 [37기 안나라] Modify: 로그인 후 위시리스트 추가 통신완료
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/components/PriceCalculator.js
Labels: 멘토 리뷰 요청

#21 [37기 안나라]Modify: 메인카테고리 이동 link 수정
  src/components/SubNav/SubNav.js
Labels: 멘토 리뷰 요청

#22 [37기 이가을] fix: CSS 수정 / Link 연결
  src/components/Login/Login.js
  src/components/Login/Login.scss
  src/components/Nav/Dropdown.js
  src/components/Nav/Dropdown.scss
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/pages/Likes/Likes.scss
  src/pages/Likes/components/LikeNull.scss
  src/styles/common.scss
  src/styles/variable.scss
Labels: 멘토 리뷰 요청
